### ISSUE TITLE
7) Handle edge cases

### ISSUE THREAD

**Issue by dam2452** [dam2452/RANCZO_KLIPY#20]
/uk - with not existing clip number e.g. /usunklip 1337

/odcinki - with random string 

/transkrypcja - with "_" as parameter

ERROR:main:<class 'aiogram.exceptions.TelegramBadRequest'> Error in TranscriptionHandler for user '2015344951': Telegram server says - Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 46
INFO:aiogram.event:Update id=612355235 is handled. Duration 240 ms by bot id=6897351570

/addsub 123 40

/addsubscription 2015344951 0

/addsubscription 999999999 30

/removewhitelist 1337

/addwhitelist 1337

/addkey 0 klucz_na_zero_dni

/addkey -30 klucz_na_ujemne_dni

/addwhitelist is broken 

/removewhitelist is also broken /wyslij too

/removewhitelist 888888888

/addkey trzydzieści klucz_tekstowy_dni

/removesubscription 2015344951

and more

**Comment by skelly37** [comment]
Albo podepnij pod odpowiedni handler podczas robienia https://github.com/dam2452/RANCZO_KLIPY/issues/22, albo jako 7)

**Comment by skelly37** [comment]
moved to https://github.com/dam2452/RANCZO_KLIPY/issues/22
