### ISSUE TITLE
4.5) Połatać handlery z nieprzechodzącymi/wykomentowanymi/brakującymi testami

### ISSUE THREAD

**Issue by skelly37** [dam2452/RANCZO_KLIPY#22]
No co tu dużo mówić, szkielet testów jest, ale samych testów trochę brakuje. Sugeruję ci zrobić sobie komentarz na zasadzie:

- [x] handlerA: link do PRa
- [x] handlerB: link do PRa
- [ ] handlerC

Będzie łatwiej śledzić progress ile tego jeszcze gnoju bedzie trzeba przepychać, no bo robić 50 issues na każdy handler to też żaden biznes. Plus że to raczej nie będzie konfliktować i możesz trzaskać po 5 branchy równolegle XD

**Comment by skelly37** [comment]
Przekleję ci te issuesy które mówiłeś że się zawierają w tym

**Comment by skelly37** [comment]
No description for /note in /admin #21

**Comment by skelly37** [comment]
# **handle edge cases**

/uk - with not existing clip number e.g. /usunklip 1337

/odcinki - with random string

/transkrypcja - with "_" as parameter

ERROR:main:<class 'aiogram.exceptions.TelegramBadRequest'> Error in TranscriptionHandler for user '2015344951': Telegram server says - Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 46
INFO:aiogram.event:Update id=612355235 is handled. Duration 240 ms by bot id=6897351570

/addsub 123 40

/addsubscription 2015344951 0

/addsubscription 999999999 30

/removewhitelist 1337

/addwhitelist 1337

/addkey 0 klucz_na_zero_dni

/addkey -30 klucz_na_ujemne_dni

/addwhitelist is broken

/removewhitelist is also broken /wyslij too

/removewhitelist 888888888

/addkey trzydzieści klucz_tekstowy_dni

/removesubscription 2015344951

and more

**Comment by dam2452** [comment]
https://github.com/dam2452/RANCZO_KLIPY/pull/24 - addwhitelist
